version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: 'arn:aws:ecs:ap-south-1:957779811736:task-definition/Blue-Green-Task:1'
        LoadBalancerInfo:
          ContainerName: 'Blue-Green-Container'
          ContainerPort: 3000
        PlatformVersion: 'LATEST'